#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh 
runApplication decomposePar -force -fileHandler collated -ioRanks '( 0 128 256 )'
runParallel reactingFoam -fileHandler collated -ioRanks '( 0 128 256 )'
